# NFP probe retrieval for the Y350a 6 nm large-random-displacement scan.

path=/eagle/APS_IRI/vnikitin/20250604
path_out=/eagle/APS_IRI/vnikitin/20250604/Y350a_FT_large_rand_disp_006nm_rec
scan_file=Y350a_FT_large_rand_disp_nobin_006nm_NFPwS_1_/Y350a_FT_large_rand_disp_nobin_006nm_NFPwS_1_0000.h5
meta_file=Y350a_FT_large_rand_disp_nobin_006nm_NFPwS_1_/ls3231-Y350a-Y350a_FT_large_rand_disp_nobin_006nm_NFPwS_1_.h5
h5_out=nfp_results.h5
dataset_ids=1
nchunk=2
n=4096
niter=513
checkpoint_step=32
error_step=32
rho=1,2,0.1
log_level=INFO
