#!/bin/bash
# Mirror this working tree to Polaris:~/holotomocupy_gpu_reduced.
#
#   ./sync_polaris.sh -n     dry run -- always do this first
#   ./sync_polaris.sh        do it
#
# Polaris becomes an exact copy of here, so anything edited ONLY on Polaris is
# destroyed.  Edit here, sync up.
#
# Reuses the ControlMaster socket from ~/.ssh/config, so an `ssh polaris` that
# is already open means no MobilePASS+ prompt.
set -euo pipefail

# The FQDN, not the `polaris` alias: a stray `Host polaris / HostName polaris`
# stanza at the top of ~/.ssh/config shadows the real one, and the bare alias
# then fails with "No route to host".
DEST=polaris.alcf.anl.gov:holotomocupy_gpu_reduced/
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/"

# --delete makes this a mirror.  Each exclusion is therefore also a promise
# NOT to delete that thing on Polaris:
#   .git            the two repos keep their own index; only the tree is synced
#   *.o[0-9]*, *.polaris-pbs-*, nodes.good.*
#                   PBS job logs (slurm-*.out, tiff-*.out, ... all carry the
#                   pbs hostname) and the healthcheck's host lists -- generated
#                   there, never here, so a mirror would delete every one
#   *.swp           someone may have the file open on Polaris
#   demo/demo_out   demo output, regenerated by ./run.sh
#   mosaic_brain/data
#                   generated test data, 130 MB, rebuilt by its gen_data.py
#   build artifacts stale ones shadow imports; each side builds its own
#
# demo/data IS copied: it is the 129 MB measured probe, and a compute node has
# no route to the internet to fetch it itself.
EXCLUDES=(
    --exclude '.git/'
    --exclude '__pycache__/'
    --exclude '*.pyc'
    --exclude '*.egg-info/'
    --exclude 'build/'
    --exclude '.ipynb_checkpoints/'
    --exclude '*.o[0-9]*'
    --exclude '*.polaris-pbs-*'
    --exclude 'slurm-*.out'
    --exclude 'nodes.good.*'
    --exclude '*.swp'
    --exclude 'tmp/'
    --exclude 'demo/demo_out/'
    --exclude 'tests/mosaic_brain/data/'
)

# PROTECT, not exclude: these are written INTO the synced tree by a run on
# Polaris, so --delete would destroy them, but when a copy does exist here it
# should still be sent.  `P` keeps the receiver's file when we have none.
# (Learned the hard way: a sync deleted a finished step7 answer for Y350c.)
PROTECT=(
    -f 'P correct_correct3D*.txt'
    -f 'P step7_it*'
    -f 'P conv*.csv'
    -f 'P shifts.png'
)

DRY=()
if [ "${1:-}" = "-n" ] || [ "${1:-}" = "--dry-run" ]; then
    DRY=(-n)
    echo "=== DRY RUN -- nothing will be written ==="
fi

rsync -a --delete --itemize-changes "${DRY[@]}" "${EXCLUDES[@]}" "${PROTECT[@]}" "$SRC" "$DEST"

echo
echo "Reinstall on Polaris ONLY when a module is added/renamed; ordinary edits"
echo "are picked up live by the editable install:"
echo "  ssh polaris"
echo "  module use /soft/modulefiles; module load conda; conda activate base"
echo "  cd ~/holotomocupy_gpu_reduced && python -m pip install -e . --user --no-deps --no-build-isolation"
